/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 15c2b356ead5189306e89ea4fac96073)
interface __BaseEnv_Env {
	SESSIONS: KVNamespace;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
