/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 218b8723742bd2a750ff5971a8b02132)
interface __BaseEnv_Env {
	SESSIONS: KVNamespace;
	DB: D1Database;
	FIREBASE_PROJECT_ID: "antinnamain";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FIREBASE_PROJECT_ID">> {}
}
